DepotSalesProcessSln/DSP.WEB/Controllers/InOutPaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DSP.Core.DTO;
using DSP.Core.Interfaces;
using DSP.Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DSP.WEB.Controllers
{
    [Authorize(Roles = "Admin")]
    public class InOutPaymentController : Controller
    {
        private IInOutPaymentService _iInOutPaymentService;
        public InOutPaymentController(IInOutPaymentService iInOutPaymentService)
        {
            _iInOutPaymentService = iInOutPaymentService;
        }
        public IActionResult GetInOutPayment(string id)
        {
            InOutPaymentDTO objDTO = _iInOutPaymentService.GetInOutPayment(id);
            return View(objDTO);
        }
        [HttpGet]
        public IActionResult SaveUpdateIncomingPayment()
        {            
            return View();
        }
        public IActionResult DeleteInOutPayment(string id)
        {
             _iInOutPaymentService.DeleteInOutPayment(id);
            return View();
        }
        [HttpPost]
        public IActionResult SaveUpdateIncomingPayment(ITN_BOVPM objiTN_BOVPM)
        {
            _iInOutPaymentService.SaveUpdateIncomingPayment(objiTN_BOVPM);
            return View();
        }

    }
}

DepotSalesProcessSln/DSP.WEB/Controllers/StockTransReqController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DSP.Core.DTO;
using DSP.Core.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DSP.WEB.Controllers
{
    public class StockTransReqController : Controller
    {
       private IITN_OPROService _oproService;

        public StockTransReqController(IITN_OPROService oproService)
        {
            _oproService = oproService;
        }


        public IActionResult Index()
        {
            ITN_OPRODTO oproDto = _oproService.GetAllStockTransferReq();
            return View(oproDto);
        }
        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }
    }
}

DepotSalesProcessSln/DSP.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DSP.WEB</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DSP.WEB</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        @*@if (User.Identity.IsAuthenticated)
        {
            if (User.IsInRole("Admin"))
            {*@

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Admin
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="CreateLicense">License Manager</a>
                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="UserManager">User Creation</a>
                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="CreateVendorCustomer">Vendor & Customer</a>
                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="">Configuration</a>


                            </div>
                        </li>
                        @*}
        }*@

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Branch
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="Index">Customer & Vendor</a>
                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="CreateRole">Stock Trans. Request</a>
                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="CreateLicense">Stock Receipt</a>
                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="CreateLicense">Stock Return</a>
                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="CreateLicense">Sales Invoice</a>
                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="CreateLicense">Sales Credit Note</a>
                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="CreateLicense">Purchase Order</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="InOutPayment" asp-action="GetInOutPayment"></a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Depot
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="Index">Customer & Vendor</a>
                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="StockTransReq" asp-action="Index">Stock Trans. Request</a>
                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="CreateLicense">Stock Receipt</a>
                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="CreateLicense">Stock Return</a>
                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="CreateLicense">Sales Invoice</a>
                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="CreateLicense">Sales Credit Note</a>
                            </div>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - DSP.WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>